# Generated by Django 6.0.3 on 2026-03-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TATA IPL 2026 - MEGA MATCH', max_length=200)),
                ('team_1_name', models.CharField(choices=[('CSK', 'Chennai Super Kings (CSK)'), ('DC', 'Delhi Capitals (DC)'), ('GT', 'Gujarat Titans (GT)'), ('KKR', 'Kolkata Knight Riders (KKR)'), ('LSG', 'Lucknow Super Giants (LSG)'), ('MI', 'Mumbai Indians (MI)'), ('PBKS', 'Punjab Kings (PBKS)'), ('RR', 'Rajasthan Royals (RR)'), ('RCB', 'Royal Challengers Bengaluru (RCB)'), ('SRH', 'Sunrisers Hyderabad (SRH)')], max_length=5, verbose_name='Team 1')),
                ('team_1_color', models.CharField(choices=[('blue', 'Blue Theme (MI, DC)'), ('yellow', 'Yellow Theme (CSK)'), ('red', 'Red Theme (RCB, PBKS)'), ('emerald', 'Emerald Theme (GT)'), ('purple', 'Purple Theme (KKR)'), ('orange', 'Orange Theme (SRH)'), ('pink', 'Pink Theme (RR)'), ('green', 'Green Theme (LSG)')], default='blue', max_length=20, verbose_name='Team 1 Theme')),
                ('team_2_name', models.CharField(choices=[('CSK', 'Chennai Super Kings (CSK)'), ('DC', 'Delhi Capitals (DC)'), ('GT', 'Gujarat Titans (GT)'), ('KKR', 'Kolkata Knight Riders (KKR)'), ('LSG', 'Lucknow Super Giants (LSG)'), ('MI', 'Mumbai Indians (MI)'), ('PBKS', 'Punjab Kings (PBKS)'), ('RR', 'Rajasthan Royals (RR)'), ('RCB', 'Royal Challengers Bengaluru (RCB)'), ('SRH', 'Sunrisers Hyderabad (SRH)')], max_length=5, verbose_name='Team 2')),
                ('team_2_color', models.CharField(choices=[('blue', 'Blue Theme (MI, DC)'), ('yellow', 'Yellow Theme (CSK)'), ('red', 'Red Theme (RCB, PBKS)'), ('emerald', 'Emerald Theme (GT)'), ('purple', 'Purple Theme (KKR)'), ('orange', 'Orange Theme (SRH)'), ('pink', 'Pink Theme (RR)'), ('green', 'Green Theme (LSG)')], default='red', max_length=20, verbose_name='Team 2 Theme')),
                ('match_time', models.DateTimeField(help_text='Match start hone ka time select karein (Timer yahan tak chalega)')),
                ('location', models.CharField(default='Narendra Modi Stadium, Ahmedabad', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Agar True hai toh yeh match website par live dikhega')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rank #1 Guaranteed', max_length=100)),
                ('price', models.IntegerField(help_text='Current Price (e.g. 1999)')),
                ('original_price', models.IntegerField(help_text='Kati hui price (e.g. 4999)')),
                ('slots_left', models.IntegerField(default=1, help_text='Kitne slots bache hain (FOMO ke liye)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='WhatsApp Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_converted', models.BooleanField(default=False, help_text='Kya is bande ne payment kar di hai?')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.package')),
            ],
        ),
    ]
