# Generated by Django 6.0.3 on 2026-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='hanumntpunb@axl', help_text='Apni active UPI ID daalein', max_length=100)),
                ('payee_name', models.CharField(default='Hanumant Meena', help_text='Bank account mein jo naam hai', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Isko tick rakhein taaki yeh live dikhe')),
            ],
            options={
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(help_text='For ex. Narendra Modi Stadium, Ahmedabad', max_length=255),
        ),
    ]
