# Generated by Django 6.0.3 on 2026-03-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentsetting_alter_match_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='utr_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UTR Number'),
        ),
    ]
