# Generated by Django 6.0.3 on 2026-03-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead_utr_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinningProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: GL Rank #1 MI vs GT', max_length=200)),
                ('youtube_url', models.URLField(help_text='Paste direct YouTube video link here')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Winning Proofs',
                'ordering': ['-created_at'],
            },
        ),
    ]
