# Generated by Django 6.0.3 on 2026-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_winningproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField(help_text='Example: 1')),
                ('amount_won', models.CharField(help_text='Example: ₹1 Crore', max_length=50)),
                ('match_name', models.CharField(help_text='Example: IND vs AUS GL', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Recent Winners',
                'ordering': ['-created_at'],
            },
        ),
    ]
