# Generated by Django 6.0.3 on 2026-03-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recentwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winningproof',
            name='winning_amount',
            field=models.CharField(default='₹1 Crore', help_text='Example: ₹57 Lakh', max_length=50),
        ),
    ]
