# Generated by Django 6.0.3 on 2026-03-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_winningproof_winning_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_link', models.URLField(default='http://t.me/rankformula1', help_text='Apne Telegram Channel/Group ka link daalein')),
                ('whatsapp_number', models.CharField(default='9461717755', help_text='WhatsApp Number daalein (Bina +91 ke)', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Isko tick rakhein taaki website par update ho jaye')),
            ],
            options={
                'verbose_name_plural': 'Site Settings (Links/WhatsApp)',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='bg_image_url',
            field=models.URLField(blank=True, help_text='Live Match div ka Background Image URL', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='poster_image_url',
            field=models.URLField(blank=True, help_text='Badges ke neeche dikhne wala Match Poster URL', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_full_name',
            field=models.CharField(default='Chennai Super Kings', help_text='Card mein dikhane ke liye pura naam', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_full_name',
            field=models.CharField(default='Mumbai Indians', help_text='Card mein dikhane ke liye pura naam', max_length=100),
        ),
    ]
