# Generated by Django 6.0.3 on 2026-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesetting_match_bg_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwinner',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Winner ki photo upload karein (Square shape best rhegi)', null=True, upload_to='winners/'),
        ),
    ]
