# Generated by Django 6.0.3 on 2026-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recentwinner_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bg_image_url',
        ),
        migrations.RemoveField(
            model_name='match',
            name='poster_image_url',
        ),
        migrations.AddField(
            model_name='match',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Live Match div ka Background Image upload karein', null=True, upload_to='match_bgs/'),
        ),
        migrations.AddField(
            model_name='match',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Badges ke neeche dikhne wala Match Poster upload karein', null=True, upload_to='match_posters/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='daily_booking_count',
            field=models.IntegerField(default=0, help_text='Kitne logo ne book kiya hai? (Fake booking alert ke liye)'),
        ),
    ]
